resolver: lts-18.22
packages:
- chap01-samples
- chap02-samples
- chap03-samples
- chap04-samples
- chap05-samples
- chap07-samples
- chap08-samples
- chap09-samples
- chap10-samples
- chap11-samples
extra-deps:
- HDBC-sqlite3-2.3.3.1
- reroute-0.6.0.0
- Spock-0.14.0.0
- Spock-core-0.14.0.0
- stm-containers-1.2
- stm-hamt-1.2.0.6
