resolver: lts-12.0
packages:
- chap01-samples
- chap02-samples
- chap03-samples
- chap04-samples
- chap05-samples
- chap07-samples
- chap08-samples
- chap09-samples
- chap10-samples
- chap11-samples
extra-deps:
- HDBC-sqlite3-2.3.3.1
- reroute-0.5.0.0
- Spock-0.13.0.0
- Spock-core-0.13.0.0
