resolver: lts-10.6
packages:
- chap01-samples
- chap02-samples
- chap03-samples
- chap04-samples
- chap05-samples
- chap07-samples
- chap08-samples
- chap09-samples
- chap10-samples
- chap11-samples
extra-deps:
- HDBC-sqlite3-2.3.3.1
